Added blacklist functionality #8
bdaase/noannoyance pull request #12
Opened 2021-07-05 14:01 UTC by skoruppa

- Fixes #8 
- Simple blacklist functionality using window's WM_CLASS. To discover window's WM_CLASS you can use
`xprop | grep WM_CLASS` command. After executing it, click on the window you want to investigate 
![image](https://user-images.githubusercontent.com/899429/124482324-71007900-dda9-11eb-824e-a48c1e1ab932.png)
you want to copy the second string 
- By default, I included `Microsoft Teams - Preview` in settings as this is the only app I have issues with
- Preference window is based on one from https://github.com/eonpatapon/gnome-shell-extension-caffeine extension
![image](https://user-images.githubusercontent.com/899429/124482818-f97f1980-dda9-11eb-9193-8ed083a3c779.png)

2021-07-09 16:29 UTC, bdaase commented
Thanks a lot for working on this, that is highly appreciated!
I hope I will find some time at the weekend to have a look at it in detail.

2021-07-11 11:55 UTC, bdaase requested changes
I now had a look at the pull request, this all looks really good and the blacklisting logic looks correct.
Just two things:
1. Was the preferences window written with GTK3 in mind? At least on Fedora it needs to be GTK4, otherwise it won't open. The conversion to GTK4 should be, maybe besides the GTKToolbar, straight. Could you convert the preferences window to be GTK4 compliant?

2. I have seen that you have added support for translations using mnemonics. AFAICS, the translations are not yet used. Where would they be placed in the tree? Can we maybe add an initial translation file then as well?

Besides that, that looks awesome and thanks a lot! Would you be able to address the change so that we can merge it quickly?

2021-07-14 13:11 UTC, skoruppa commented
1. Yeah, GTK3 in mind, because I'm still using Ubuntu 20.04 (requirement from the corporation I'm working in, is to use LTS Ubuntu). So I can't rewrite the preferences window to GTK4, at least for now 

2. Sure, I will add some initial translation to my pull request

2021-07-18 16:34 UTC, bdaase commented
> 1. Yeah, GTK3 in mind, because I'm still using Ubuntu 20.04 (requirement from the corporation I'm working in, is to use LTS Ubuntu). So I can't rewrite the preferences window to GTK4, at least for now

Hmm, this is somehow unfortunate, as the GTK3 preference window crashes at least on Fedora 34. So id idfef'ing it for GTK3/4 the way to go here?
> 2. Sure, I will add some initial translation to my pull request

Perfect, thanks.

2022-01-26 02:00 UTC, bernkat commented
Any updates on this PR? I would really like the ability to blacklist Telegram Desktop.

2022-04-29 13:50 UTC, skoruppa commented
I finally upgraded from the previous LTS to the new one so I had a chance to play with GTK4. Decided to ditch translations.
Because of GTK4 the preference window will work only with Gnome 40+

2022-04-29 16:19 UTC, bdaase reviewed
@skoruppa Awesome, thanks a lot! I just gave it a try, and it works great!

The changes LGTM.  I can't really comment on the GTK side of things, but it seems to work, so also good from my side.
I just added a few nitpicks.

2022-04-29 16:19 UTC, bdaase commented on prefs.js
> +        title: "WM__CLASS List",
Maybe add a hint to the string on how to get the wmclass?

What works for both wayland and x11 windows is >Alt + F2 -> lg -> Windows.

2022-04-29 16:19 UTC, bdaase commented on extension.js
> +        global.log("stealing focus ignored");
Could you make this log title case please?

2022-04-29 16:19 UTC, bdaase commented on schemas/org.gnome.shell.extensions.noannoyance.gschema.xml
> +      <description>If set, it will prevent defined applications (by wm_class) from stealing focus.</description>
it would be great to unify the (user facing) strings for WM class (you currently use WM class, WM_CLASS, wm_class).

2022-07-05 18:12 UTC, skoruppa commented
Merged changes from #16

2022-07-06 15:42 UTC, bdaase approved these changes
Thanks for the work, LGTM!

2022-07-06 15:43 UTC, merged